# SwiftLint Configuration for NoteTaker

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - force_unwrapping
  - redundant_optional_initialization
  - private_outlet
  - closure_spacing

excluded:
  - Pods
  - DerivedData
  - .build
  - NoteTaker.xcdatamodeld

line_length:
  warning: 120
  error: 150
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

force_cast: error
force_try: error
force_unwrapping: warning

reporter: "xcode"
